# Solución Tarea 1: Numpy

# Problema 1

Parte a

In [8]:
import numpy as np

In [13]:
# con np.asarray: tenemos que ingresar fila por fila
A = np.asarray([[1,2,3],[4,5,6],[7,8,9]])
# Verifiquemos que todo está bien
print A
print A.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


Parte b

In [15]:
# primero un array que va de 1 a 9, y hacemos un reshape
A1 = np.arange(1,10).reshape(3,3)
print A1
print A1.shape
# Verifiquemos que tienen los mismos elementos----> Qué estoy haciendo con el .mean()?
print (A==A1).mean()


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1.0


Parte c

In [ ]:
# inicialicemos la matriz:
A3 = np.zeros((3,3))
# vamos a usar un contador para llenar la matriz
counter = 1
for i in range(3):
    for j in range(3):
        A3[i,j] = counter
        # Actualicemos el contador
        counter +=1
print A3
print A3.shape
print (A3==A1).mean()

Parte d

In [ ]:
# método uno, como es una matriz chica podemos hacerlo sin loops
Adiag = np.asarray([A[0,0], A[1,1], A[2,2]])
# con un "list comprehension"
Adiag_lc = [A[i,i] for i in range(3)]
# miremos que son iguales
print (Adiag==Adiag_lc).mean()

Parte e

In [20]:
# usando la función np.diag
Adiag_numpy =  np.diag(A)
print Adiag_numpy

[1 5 9]


# Problema 2

Parte a

In [22]:
b = np.asarray([-1,2,1]).reshape((1,3))
print b.shape

(1, 3)


Parte b

In [23]:
Ab = np.dot(A,b)

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

### El problema es que las matrices no son conformes para la multiplicación, como el error nos dice.  La solución es muy simple: np.reshape()

In [25]:
Ab = np.dot(A,b.reshape(3,1))

Parte c

In [31]:
# inicialicemos la matriz
Ab_loop = np.zeros((3,1))
# hay que hacer un loop sobre las filas de A
for r in range(3):
    Ab_loop[r] = np.dot(A[r,:].reshape(1,3),b.reshape(3,1))
    
# miremos que todo está bien
print (Ab== Ab_loop).mean()

1.0


Parte d

In [34]:
# inicialicemos la nueva matriz
Ab_loop2 = np.zeros((3,1))
# loop externo es sobre lo elementos del nuevo vector
for k in range(3):
    # Loop sobre la suma que define a cada elemento k
    suma_k = 0
    for j in range(3):
        # necesitamos seleccionar el elemento j de la fila k de A
        suma_k += A[k,j]*b[0,j]
    # Fin del for, así que podemos asignar
    Ab_loop2[k] = suma_k

print Ab_loop2
print (Ab_loop==Ab_loop2).mean()

[[  6.]
 [ 12.]
 [ 18.]]
1.0


# Problema 3

Parte 1

In [36]:
# generemos los vectores
vec1 = np.arange(99)
vec2 = 20*np.ones((99))
print vec1.shape, vec2.shape


(99,) (99,)


Parte 2

In [37]:
# usemos timeit
%timeit np.add(vec1,vec2)

The slowest run took 18.23 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.43 µs per loop


In [44]:
# revisemos que la función está haciendo lo que queremos: el primer elemento es 20+0, el segundo 20+1, 
#  y así sucesivamente
print np.add(vec1,vec2)

[  20.   21.   22.   23.   24.   25.   26.   27.   28.   29.   30.   31.
   32.   33.   34.   35.   36.   37.   38.   39.   40.   41.   42.   43.
   44.   45.   46.   47.   48.   49.   50.   51.   52.   53.   54.   55.
   56.   57.   58.   59.   60.   61.   62.   63.   64.   65.   66.   67.
   68.   69.   70.   71.   72.   73.   74.   75.   76.   77.   78.   79.
   80.   81.   82.   83.   84.   85.   86.   87.   88.   89.   90.   91.
   92.   93.   94.   95.   96.   97.   98.   99.  100.  101.  102.  103.
  104.  105.  106.  107.  108.  109.  110.  111.  112.  113.  114.  115.
  116.  117.  118.]


Parte 3

In [51]:
# Usemos la función exec como en las notas de clase

In [46]:
# inicialicemos
vec_sum = np.zeros((99))
for i in range(99):
    vec_sum[i] = vec1[i] + vec2[i]
    

In [52]:
%timeit exec(In[46])

1000 loops, best of 3: 364 µs per loop


In [54]:
# calculemos la ganancia en velocidad
ganancia_vel = 364/1.43
print ganancia_vel

254.545454545


#### El loop es 254 veces más lento que la función univeral

Parte 4

In [55]:
# hagamos la suma directa
%timeit vec1+vec2

The slowest run took 18.09 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.44 µs per loop


Parte 5

**La suma directa en NumPy es igual de rápida!  De hecho son la misma función universal**

# Problema 4


Parte a

In [56]:
x = np.arange(20).reshape((20,1))

Parte b


In [57]:
y = np.random.randn(20,1)

Parte b1

La función `np.random.randn(d1,d2,...,dk)` genera un vector multidimensional (k dimensiones) de números aleatorios distribuidos normal estándar.  Las dimensiones las pasa el usuario como argumento.

Parte c

In [59]:
# medias muestrales
xbar = x.mean()
ybar = y.mean()

Parte d

In [60]:
# inicialicemos la matriz
DistMat = np.zeros((20,20))
# loop externo: controla las filas
for i in range(20):
    # loop interno: controla las columnas
    for j in range(20):
        DistMat[i,j] = (x[i]-xbar)**2 + (y[j]-ybar)**2

In [62]:
# Miremos que quedó bien seleccionando dos elementos a mano:
# A. Uno sobre la diagonal:
print DistMat[0,0]
# B. Cómo debería ser?
d00 = (x[0]-xbar)**2 + (y[0]-ybar)**2
print d00

91.4543023202
[ 91.45430232]


Parte d


In [63]:
%timeit exec(In[60])

100 loops, best of 3: 3.71 ms per loop


Parte e

Si no lo han leído, dejo que lo hagan por su [cuenta](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

In [67]:
# El ejemplo más sencillo es la suma de dos vectores que no son conformes para la suma:
colvec = np.array([1,2,3,4]).reshape((4,1))
rowvec = np.array([10,20]).reshape((1,2))
# yo quiero obtener la matriz M_{i,j} = c_{i} + r_{j}
# Noten que en principio esto no puede hacerse con reglas algebraícas matriciales
# Pero si con broadcasting
broad_sum = colvec + rowvec
print broad_sum

[[11 21]
 [12 22]
 [13 23]
 [14 24]]


Parte f

In [69]:
# Con broadcasting es muy simple:
# Primer paso: encontremos los vectores sin las medias elevados al cuadrado
x_demean = (x-xbar)**2
y_demean = (y-ybar)**2
# Revisemos que todo está como creemos que debe estar
print x_demean.shape, x.shape, y_demean.shape, y.shape


(20, 1) (20, 1) (20, 1) (20, 1)


In [70]:
# Segundo paso: broadcasting:
Dmat_broad = x_demean.reshape((20,1)) + y_demean.reshape((1,20))
print (DistMat==Dmat_broad).mean()

1.0


In [71]:
# finalmente miremos cuánto se demora NumPy haciendo todo
x_demean = (x-xbar)**2
y_demean = (y-ybar)**2
Dmat_broad = x_demean.reshape((20,1)) + y_demean.reshape((1,20))

In [72]:
%timeit exec(In[71])

10000 loops, best of 3: 67.3 µs per loop


In [73]:
# Con broadcasting: 67.3 microsegundos
# Con loops: 3.7 milisegundos:
# recordemos que un microsegundo es 1E(-3) milisegundos

In [78]:
ganancia_vel = 3.7/(67.31E-3)
print ganancia_vel

54.9695439014
